server:
  port: 8091

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: routes-product-service
          uri: http://localhost:7001/product
          predicates:
            - Path=/product/**
          filters: #配置全局过滤器
            - StripPrefix=1
            - Auth
        - id: routes-connsumer-service
          uri: http://localhost:7001
          predicates:
            - Path=/consumer/**
          filters: #配置全局过滤器
            - StripPrefix=1
            - Auth
eureka:
  client:
    service-url:
      #defaultZone 这个是不会提示的，此处需要自己写
      #实际上属性应该是service-url,这个属性是个map（key-value）格式；当key是defaultZone的时候才能被解析；所以这里没有提示，
      #但是自己还需要写一个defaultZone；
      defaultZone: http://localhost:8090/eureka/